spring:
  banner:
    location: classpath:banner.txt
  datasource:
    url: jdbc:postgresql://localhost:3000/evently
    username: postgres
    password: ""
    driverClassName: org.postgresql.Driver
  jpa:
    database: postgresql
    databasePlatform: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379
      password: ""
      database: 0
